name: Build latest
on: [push]

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  build-mono:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile MCGalaxy using mono
        shell: bash
        id: compile
        env: 
          CONFIGURATION: "Debug"
        run: |
          msbuild MCGalaxy.sln
          zip MCGalaxy-net.zip bin/Debug/MCGalaxy.exe bin/Debug/MCGalaxyCLI.exe bin/Debug/MCGalaxy_.dll

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile MCGalaxy .NET build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'MCGalaxy-net.zip'
          DEST_NAME: 'MCGalaxy-net.zip'